version: '3'
services:

  auth-bd:
    image: postgres:16
    container_name: auth-bd
    restart: always
    environment:
      - POSTGRES_DB=auth-bd
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=123456789
    ports:
      - 5435:5432
  
  product-db:
    image: postgres:16
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
  
  vendas-db:
    image: postgres:16
    container_name: vendas-db
    restart: always
    environment:
      - POSTGRES_DB=vendas-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432
  
  vendas-rabbit:
    image: rabbitmq:3-management
    container_name: vendas-rabbit
    restart: always
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672


  